<a href="https://colab.research.google.com/github/hariskhan-hk/Numpy_PracQues/blob/main/LAB1_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np

In [44]:
#QUESTION NO 02

data1 = np.array([1,3,9,12,18]) #1D Array
data2 = np.array([[1,5,2,0],[3,6,4,7]]) #2D Array
data3 = np.array([['7','6'],['5','4'],['3','2']]) #2D Array with string elements
data4 = np.array([[11,52,20,50], [34,61,43,17]]) #2D Array

print("Data1:", data1)
print("Data2:", data2)
print("Data3:", data3)
print("Data4:", data4)

Data1: [ 1  3  9 12 18]
Data2: [[1 5 2 0]
 [3 6 4 7]]
Data3: [['7' '6']
 ['5' '4']
 ['3' '2']]
Data4: [[11 52 20 50]
 [34 61 43 17]]


In [36]:
#QUESTION NO 03

data1_add = data1 + data1
print(data1_add)
data1_mul = data1 * 10
print(data1_mul)

data1 = data1.astype(int)
data2 = data1.astype(int)
data3 = data1.astype(int)
data4 = data1.astype(int)

[ 2  6 18 24 36]
[ 10  30  90 120 180]


In [37]:
#QUESTION NO 04

array_zeros = np.zeros((3,5))
array_ones = np.ones((2,8))
array_random = np.random.normal(size = (6,3))

print(array_zeros)
print(array_ones)
print(array_random)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[ 0.86077871  0.68029351  1.03704388]
 [-0.46023125 -0.39227444 -0.21649747]
 [ 0.9355863  -1.79760912  0.44800645]
 [-0.89737753 -0.08681704  0.02064853]
 [-0.26160074 -1.49244218 -0.35157672]
 [ 0.76116554  0.41412774 -2.15263199]]


In [46]:
#QUESTION NO 05

sq_data1 = data1[2:4]**2
sq_data2 = data2[[0, 1], [1, 2]]
sq_data2 = sq_data2**2

print(sq_data1)
print(sq_data2)

[ 81 144]
[25 16]


In [48]:
#QUESTION NO 06

Subjects = np.array([['ML', 'OS', 'CCN'], ['OS', 'AI', 'MP'], ['CCN', 'ML', 'AI']])
Subjects[(Subjects!='ML') & (Subjects!='AI')] = 0

print(Subjects)

[['ML' '0' '0']
 ['0' 'AI' '0']
 ['0' 'ML' 'AI']]
