<a href="https://colab.research.google.com/github/hariskhan-hk/Numpy_PracQues/blob/main/LAB1_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np

In [27]:
#QUESTION NO 02

data1 = np.array([1,3,9,12,18]) #1D Array
data2 = np.array([[1, 5, 2, 0],[3, 6, 4, 7]]) #2D Array
data3 = np.array([['7','6'],['5','4'],['3','2']]) #2D Array with string elements
data4 = np.array([[11,52,20,50], [34,61,43,17]]) #2D Array

print("Data1:", data1)
print("Data2:", data2)
print("Data3:", data3)
print("Data4:", data4)

Data1: [ 1  3  9 12 18]
Data2: [[1 5 2 0]
 [3 6 4 7]]
Data3: [['7' '6']
 ['5' '4']
 ['3' '2']]
Data4: [[11 52 20 50]
 [34 61 43 17]]


In [28]:
#QUESTION NO 03

data1_add = data1 + data1
print(data1_add)
data1_mul = data1 * 10
print(data1_mul)

data1 = data1.astype(int)
data2 = data2.astype(int)
data3 = data3.astype(int)
data4 = data4.astype(int)

[ 2  6 18 24 36]
[ 10  30  90 120 180]


In [29]:
#QUESTION NO 04

array_zeros = np.zeros((3,5))
array_ones = np.ones((2,8))
array_random = np.random.normal(size = (6,3))

print(array_zeros)
print(array_ones)
print(array_random)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[ 2.43654571e-01  2.80975662e-01 -4.42166356e-01]
 [-1.93133895e-01 -1.69421932e-01 -3.52567549e-01]
 [-1.91548336e+00 -7.76181379e-01  1.93811121e+00]
 [-7.51062932e-01  1.43868546e+00 -1.01149543e+00]
 [-1.01147422e+00  1.11223889e+00  4.19691702e-02]
 [ 1.68461079e-04 -9.32651288e-01 -1.35566916e+00]]


In [30]:
# #QUESTION NO 05

sq_data1 = data1[2:4]
print(sq_data1**2)

sq_data2= data2[[0, 1], [1, 2]]
print(sq_data2**2)

[ 81 144]
[25 16]


In [31]:
#QUESTION NO 06

Subjects = np.array([['ML', 'OS', 'CCN'], ['OS', 'AI', 'MP'], ['CCN', 'ML', 'AI']])
Subjects[(Subjects!='ML') & (Subjects!='AI')] = 0

print(Subjects)

[['ML' '0' '0']
 ['0' 'AI' '0']
 ['0' 'ML' 'AI']]


In [32]:
#QUESTION NO 07

data2_transposed = np.transpose(data2)
data3_transposed = np.transpose(data3)
data4_transposed = np.transpose(data4)

print(data2_transposed)
print(data3_transposed)
print(data4_transposed)

[[1 3]
 [5 6]
 [2 4]
 [0 7]]
[[7 5 3]
 [6 4 2]]
[[11 34]
 [52 61]
 [20 43]
 [50 17]]


In [33]:
#QUESTION NO 08

concatenated_vertically = np.vstack((data2, data4))
concatenated_horizontally = np.hstack((data2, data4))

print("Concatenated using vstack:", concatenated_vertically)
print("Concatenated using hstack:", concatenated_horizontally)

Concatenated using vstack: [[ 1  5  2  0]
 [ 3  6  4  7]
 [11 52 20 50]
 [34 61 43 17]]
Concatenated using hstack: [[ 1  5  2  0 11 52 20 50]
 [ 3  6  4  7 34 61 43 17]]


In [34]:
#QUESTION NO 09

mean_data2 = np.mean(data2, axis=0)

demeaned_data2 = data2 - mean_data2
print("Demeaned Data2:", demeaned_data2)

Demeaned Data2: [[-1.  -0.5 -1.  -3.5]
 [ 1.   0.5  1.   3.5]]


In [35]:
#QUESTION NO 10

reshaped_data2 = np.reshape(data2, (4, 2))

print("Reshaped Data2:", reshaped_data2)


Reshaped Data2: [[1 5]
 [2 0]
 [3 6]
 [4 7]]


In [36]:
#QUESTION NO 11

marks_table = np.array([
    [60, 70, 50],  # Subject1
    [40, 60, 80],  # Subject2
    [70, 55, 65]   # Subject3
])

max_scores_per_subject = np.max(marks_table, axis=1)

print("Maximum scores per subject:")
print("Subject1:", max_scores_per_subject[0])
print("Subject2:", max_scores_per_subject[1])
print("Subject3:", max_scores_per_subject[2])

Maximum scores per subject:
Subject1: 70
Subject2: 80
Subject3: 70


In [37]:
#QUESTION NO 12

def grade_point(marks):
    conditions = [
        marks >= 94,
        np.logical_and(marks >= 85, marks <= 93),
        np.logical_and(marks >= 80, marks <= 84),
        np.logical_and(marks >= 75, marks <= 79),
        np.logical_and(marks >= 70, marks <= 74),
        np.logical_and(marks >= 67, marks <= 69),
        np.logical_and(marks >= 64, marks <= 66),
        np.logical_and(marks >= 60, marks <= 63),
        np.logical_and(marks >= 57, marks <= 59),
        np.logical_and(marks >= 54, marks <= 56),
        np.logical_and(marks >= 50, marks <= 53),
        marks < 50
    ]
    grade_points = np.select(conditions, [4.0, 4.0, 3.7, 3.4, 3.0, 2.7, 2.4, 2.0, 1.7, 1.4, 1.0, 0.0])
    return grade_points

def calculate_cgpa(student_marks, student_credits):
    grade_points = grade_point(student_marks)
    total_credits = np.sum(student_credits)
    if total_credits > 0:
        cgpa = np.sum(grade_points * student_credits) / total_credits
        return cgpa
    else:
        print("Error: No credits found for the student.")
        return None

student1_marks = np.array([60, 40, 70])
student1_credits = np.array([2, 3, 4])

student2_marks = np.array([70, 60, 55])
student2_credits = np.array([2, 3, 4])

student3_marks = np.array([50, 80, 65])
student3_credits = np.array([2, 3, 4])

# Calculate CGPA for each student
student1_cgpa = calculate_cgpa(student1_marks, student1_credits)
student2_cgpa = calculate_cgpa(student2_marks, student2_credits)
student3_cgpa = calculate_cgpa(student3_marks, student3_credits)

print("Student 1 CGPA:", student1_cgpa)
print("Student 2 CGPA:", student2_cgpa)
print("Student 3 CGPA:", student3_cgpa)


Student 1 CGPA: 1.7777777777777777
Student 2 CGPA: 1.9555555555555557
Student 3 CGPA: 2.5222222222222226
