<a href="https://colab.research.google.com/github/hariskhan-hk/Numpy_PracQues/blob/main/LAB1_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np

In [46]:
#QUESTION NO 02 - Create an ndarray using the following data. Write the code and outputs.
#                                                ′7′ ′6′
#                              1 𝟓 2 0           ′5′ ′4′           11 52 20 50
# 𝐷𝑎𝑡𝑎1 = 1 3 𝟗 𝟏𝟐 18, 𝐷𝑎𝑡𝑎2 = 3 6 𝟒 7,  𝐷𝑎𝑡𝑎3 = ′3′ ′2′ , 𝐷𝑎𝑡𝑎4 = 34 61 43 17

data1 = np.array([1,3,9,12,18]) #1D Array
data2 = np.array([[1, 5, 2, 0],[3, 6, 4, 7]]) #2D Array
data3 = np.array([['7','6'],['5','4'],['3','2']]) #2D Array with string elements
data4 = np.array([[11,52,20,50], [34,61,43,17]]) #2D Array

print("Data1:", data1)
print("Data2:", data2)
print("Data3:", data3)
print("Data4:", data4)

Data1: [ 1  3  9 12 18]
Data2: [[1 5 2 0]
 [3 6 4 7]]
Data3: [['7' '6']
 ['5' '4']
 ['3' '2']]
Data4: [[11 52 20 50]
 [34 61 43 17]]


In [47]:
#QUESTION NO 03 - Add Data1 in Data1. Multiply Data1 by 10. Convert Data1, Data2, Data3, and Data4 datatypes to integer.

data1_add = data1 + data1
print(data1_add)
data1_mul = data1 * 10
print(data1_mul)

data1 = data1.astype(int)
data2 = data2.astype(int)
data3 = data3.astype(int)
data4 = data4.astype(int)

[ 2  6 18 24 36]
[ 10  30  90 120 180]


In [48]:
#QUESTION NO 04 - Create a 3x5 array of 0s. 2x8 array of 1s, 6x3 array of integer random numbers.

array_zeros = np.zeros((3,5))
array_ones = np.ones((2,8))
array_random = np.random.normal(size = (6,3))

print(array_zeros)
print(array_ones)
print(array_random)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[ 1.06508331  1.12918349 -0.17575962]
 [-1.04289011  0.58233996  0.33690411]
 [-0.3773833   0.53630828 -0.06121706]
 [-0.61708386  0.05604     2.64230456]
 [ 0.58852249  0.20913986 -1.60691912]
 [ 2.11043096  0.09997955 -0.30906108]]


In [49]:
# #QUESTION NO 05 - Square the bold elements of Data1 and Data2. Hint: use indexing and slicing.

sq_data1 = data1[2:4]
print(sq_data1**2)

sq_data2= data2[[0, 1], [1, 2]]
print(sq_data2**2)

[ 81 144]
[25 16]


In [50]:
                                               # 𝑀𝐿 𝑂𝑆 𝐶𝐶𝑁
#QUESTION NO 06 - Consider an array Subjects = # 𝑂𝑆 𝐴𝐼 𝑀𝑃 . Set all courses to 0 except ML and AI. Hint: use Boolean indexing.
                                               # 𝐶𝐶𝑁 𝑀𝐿 𝐴𝐼

Subjects = np.array([['ML', 'OS', 'CCN'], ['OS', 'AI', 'MP'], ['CCN', 'ML', 'AI']])
Subjects[(Subjects!='ML') & (Subjects!='AI')] = 0

print(Subjects)

[['ML' '0' '0']
 ['0' 'AI' '0']
 ['0' 'ML' 'AI']]


In [51]:
#QUESTION NO 07 - Transpose the Data2, Data3, and Data4 arrays using appropriate function

data2_transposed = np.transpose(data2)
data3_transposed = np.transpose(data3)
data4_transposed = np.transpose(data4)

print(data2_transposed)
print(data3_transposed)
print(data4_transposed)

[[1 3]
 [5 6]
 [2 4]
 [0 7]]
[[7 5 3]
 [6 4 2]]
[[11 34]
 [52 61]
 [20 43]
 [50 17]]


In [52]:
#QUESTION NO 08 - Concatenate Data2 and Data4 using vstack and hstack.

concatenated_vertically = np.vstack((data2, data4))
concatenated_horizontally = np.hstack((data2, data4))

print("Concatenated using vstack:", concatenated_vertically)
print("Concatenated using hstack:", concatenated_horizontally)

Concatenated using vstack: [[ 1  5  2  0]
 [ 3  6  4  7]
 [11 52 20 50]
 [34 61 43 17]]
Concatenated using hstack: [[ 1  5  2  0 11 52 20 50]
 [ 3  6  4  7 34 61 43 17]]


In [53]:
#QUESTION NO 09 - Demean each column of Data2. Hint: use broadcasting

mean_data2 = np.mean(data2, axis=0)

demeaned_data2 = data2 - mean_data2
print("Demeaned Data2:", demeaned_data2)

Demeaned Data2: [[-1.  -0.5 -1.  -3.5]
 [ 1.   0.5  1.   3.5]]


In [54]:
#QUESTION NO 10 - Convert Data2 shape into 4x2. Hint: Use reshape function.

reshaped_data2 = np.reshape(data2, (4, 2))

print("Reshaped Data2:", reshaped_data2)


Reshaped Data2: [[1 5]
 [2 0]
 [3 6]
 [4 7]]


In [55]:
#QUESTION NO 11 - Consider the table having marks of three students scored in three subjects. Compute the maximum score of each subject. Hint: use max function

marks_table = np.array([
    [60, 70, 50],  # Subject1
    [40, 60, 80],  # Subject2
    [70, 55, 65]   # Subject3
])

max_scores_per_subject = np.max(marks_table, axis=1)

print("Maximum scores per subject:")
print("Subject1:", max_scores_per_subject[0])
print("Subject2:", max_scores_per_subject[1])
print("Subject3:", max_scores_per_subject[2])

Maximum scores per subject:
Subject1: 70
Subject2: 80
Subject3: 70


In [56]:
#QUESTION NO 12 - Compute the CGPA of all three students using the following formula and tables 1.11 and 1.12 (Hint: Use ufunc methods).

def grade_point(marks):
    conditions = [
        marks >= 94,
        np.logical_and(marks >= 85, marks <= 93),
        np.logical_and(marks >= 80, marks <= 84),
        np.logical_and(marks >= 75, marks <= 79),
        np.logical_and(marks >= 70, marks <= 74),
        np.logical_and(marks >= 67, marks <= 69),
        np.logical_and(marks >= 64, marks <= 66),
        np.logical_and(marks >= 60, marks <= 63),
        np.logical_and(marks >= 57, marks <= 59),
        np.logical_and(marks >= 54, marks <= 56),
        np.logical_and(marks >= 50, marks <= 53),
        marks < 50
    ]
    grade_points = np.select(conditions, [4.0, 4.0, 3.7, 3.4, 3.0, 2.7, 2.4, 2.0, 1.7, 1.4, 1.0, 0.0])
    return grade_points

def calculate_cgpa(student_marks, student_credits):
    grade_points = grade_point(student_marks)
    total_credits = np.sum(student_credits)
    if total_credits > 0:
        cgpa = np.sum(grade_points * student_credits) / total_credits
        return cgpa
    else:
        print("Error: No credits found for the student.")
        return None

student1_marks = np.array([60, 40, 70])
student1_credits = np.array([2, 3, 4])

student2_marks = np.array([70, 60, 55])
student2_credits = np.array([2, 3, 4])

student3_marks = np.array([50, 80, 65])
student3_credits = np.array([2, 3, 4])

# Calculate CGPA for each student
student1_cgpa = calculate_cgpa(student1_marks, student1_credits)
student2_cgpa = calculate_cgpa(student2_marks, student2_credits)
student3_cgpa = calculate_cgpa(student3_marks, student3_credits)

print("Student 1 CGPA:", student1_cgpa)
print("Student 2 CGPA:", student2_cgpa)
print("Student 3 CGPA:", student3_cgpa)


Student 1 CGPA: 1.7777777777777777
Student 2 CGPA: 1.9555555555555557
Student 3 CGPA: 2.5222222222222226


In [57]:
#QUESTION NO 13 - Compute the sorted unique values in subjects array

subjects = np.array([
    ['ML', 'OS', 'CCN'],
    ['OS', 'AI', 'MP'],
    ['CCN', 'ML', 'AI']
])

unique_subjects = np.unique(subjects)
print(unique_subjects)


['AI' 'CCN' 'ML' 'MP' 'OS']


In [58]:
#QUESTION NO 14 - Compute the dot product and inverse of 4x4 random matrix. Hint: Use numpy.linalg functions.

matrix = np.random.rand(4, 4)

dot_product = np.dot(matrix, matrix)
print("Dot product of the matrix with itself:\n", dot_product)

try:
  matrix_inv = np.linalg.inv(matrix)
  print("Inverse of the matrix:\n", matrix_inv)
except np.linalg.LinAlgError as e:
  print("Error: Matrix is not invertible.", e)


Dot product of the matrix with itself:
 [[1.70615878 1.65654169 1.50420038 1.80001488]
 [1.59729009 1.55748238 1.3939179  1.4144448 ]
 [1.30036197 1.25036036 1.19584477 1.13364033]
 [1.78433196 1.76433432 1.53181459 2.09015747]]
Inverse of the matrix:
 [[-15.42043709  -7.99393053  16.72202629   9.98831646]
 [ 17.08736218  10.34655842 -20.10392028 -10.49542023]
 [  0.05979334  -1.18289145   0.49403806   0.85393056]
 [ -0.88740131  -0.65832746   2.77125715  -0.09450333]]


In [59]:
#QUESTION NO 15 - Store all the created arrays on disk.

#There are many arrays, some are shown to be stored on disk

#Save on disk in an uncompressed file
np.savez('lab1_allarrays.npz', data1 = data1, data2 = data2, data3 = data3, data4 = data4, array_zeros = array_zeros, array_ones = array_ones, array_random = array_random)

#OR

#Save on disk in a compressed file
np.savez_compressed('lab1_allarrays_compressed.npz', data1 = data1, data2 = data2, data3 = data3, data4 = data4, array_zeros = array_zeros, array_ones = array_ones, array_random = array_random)