<a href="https://colab.research.google.com/github/hariskhan-hk/Numpy_PracQues/blob/main/LAB1_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
#QUESTION NO 02

Data1 = np.array([1,3,9,12,18]) #1D Array
Data2 = np.array([[1,5,2,0],[3,6,4,7]]) #2D Array
Data3 = np.array([['7','6'],['5','4'],['3','2']]) #2D Array with string elements
Data4 = np.array([[11,52,20,50], [34,61,43,17]]) #2D Array

print("Data1:", Data1)
print("Data2:", Data2)
print("Data3:", Data3)
print("Data4:", Data4)

Data1: [ 1  3  9 12 18]
Data2: [[1 5 2 0]
 [3 6 4 7]]
Data3: [['7' '6']
 ['5' '4']
 ['3' '2']]
Data4: [[11 52 20 50]
 [34 61 43 17]]


In [11]:
#QUESTION NO 03

Data1_add = Data1 + Data1
print(Data1_add)
Data1_mul = Data1 * 10
print(Data1_mul)

Data1 = Data1.astype(int)
Data2 = Data1.astype(int)
Data3 = Data1.astype(int)
Data4 = Data1.astype(int)

[ 2  6 18 24 36]
[ 10  30  90 120 180]
